CREATE TABLE IF NOT EXISTS POSTS (
    id BIGSERIAL PRIMARY KEY, 
    title VARCHAR NOT NULL, 
    content TEXT NOT NULL, 
    author_id BIGINT REFERENCES USERS(id) ON DELETE CASCADE NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS created_at ON POSTS(created_at);
CREATE INDEX IF NOT EXISTS author_id ON POSTS(author_id);