CREATE TABLE IF NOT EXISTS USERS (
    id BIGSERIAL PRIMARY KEY, 
    username VARCHAR UNIQUE NOT NULL, 
    email VARCHAR UNIQUE NOT NULL, 
    password_hash VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS username ON USERS(username);
CREATE INDEX IF NOT EXISTS email ON USERS(email);
